itemss = {
    'mobdrop':[
        'pogchop',
        'cooked_pogchop',
        'beef',
        'steak',
        'wool',
        'map_scrap',
        'map',
        'wither_skull',
        'blaze_rod',
        'blaze_powder',
        'ender_pearl',
        'eye_of_ender'
    ],
    'misc':[
        'emerald',
        'cobble',
        'coal',
        'iron_ingot',
        'diamond',
        'gold_ingot',
        'netherite_scrap',
        'netherite_ingot',
        'redstone',
        'soul_sand',
        'wood',
        'bed',
        'common_chest',
        'rare_chest',
        'super_rare_chest',
        'epic_chest',
        'mythic_chest',
        'legendary_chest'
    ],
    'farm':[
        'small_sapling',
        'medium_sapling',
        'large_sapling',
        'apple',
        'wheat_seeds',
        'wheat',
        'potato',
        'poisonous_potato',
        'carrot',
        'beetroot_seeds',
        'beetroot',
        'cleansed_water_bucket',
        'cleansed_dirt',
        'farmlist'
    ],
    'illegal':[
        'bedrock',
        'bedrock_trophy',
        'pog_champ'
    ]
}

armors = [
    'helmet',
    'chestplate',
    'leggings',
    'boots',
    'sword'
]

statss = [
    'hp',
    'level',
    'highestArea',
    'atk',
    'defend',
    'xp',
    'area',
    'voteCount'
]